### ISSUE TITLE
Problems about evaluation

### ISSUE THREAD

**Issue by Sun-god-pineapple** [anitarau/simcol#1]
Thanks for your excellent work!
I have some problems about evaluation.
1. I only found script that evaluate depth estimates for subtask1,  could you please post the scripts for evaluating pose estimation in subtasks 2 and subtask3 at your convenience?
2. There are codes below in "eval_synthetic_depth.py", however, I couldn' t find files related to "SyntheticColon_III_Test" on the challenge website.
![1660818901378](https://user-images.githubusercontent.com/87853024/185375045-a547c98f-6bd7-4657-b48b-8f4f59be7e2d.png)
 Looking forward to your reply, thank you so much!

**Comment by anitarau** [comment]
I have added a script for evaluating subtask 2 and will add a script for subtask 3 asap. Regarding 2., I have adjusted the sharing settings on Synapse. You should now see all 9 synthetic test sequences. Thanks for raising these issues!

**Comment by Sun-god-pineapple** [comment]
Thank you very much!!!
