### ISSUE TITLE
Your request to access this dataset has been sent. What is the next step?

### ISSUE THREAD

**Issue by Hellcat1005** [anitarau/simcol#4]
Hello, I have sent my request to access the dataset. I do not know what the next step is. Will I receive an email or something else? How long will the verify take?

**Comment by wanghao-cv** [comment]
you mean the access to endomapper? I trapped in this section too.Has this problem solved?

**Comment by anitarau** [comment]
You'll have to contact the EndoMapper authors; unfortunately, I can't help with this. Contact information is provided in the EndoMapper paper.
